language: node_js

node_js:
  - "7"

sudo: falsegit

branches:
  only:
    - develop

cache:
  directories:
    - node_modules

# https://github.com/juliangruber/electron-stream#travis
addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - yarn install

before_script:
  - git config --global user.name "eldorplus"
  - git config --global user.email "eldorplus@gmail.com"
  - git clone --branch gh-pages https://${GH_REF} dist

script:
  - yarn test

#before_install:
#  - export TRAVIS_COMMIT_MSG="[deploy] $(git log --format='%h - %B' --no-merges -n 1)"
#  - export TRAVIS_COMMIT_USER="$(git log --no-merges -n 1 --format=%an)"
#  - export TRAVIS_COMMIT_EMAIL="$(git log --no-merges -n 1 --format=%ae)"
after_success:
#  - sh build/cli/deploy-ci.sh
  - yarn run build
  - cd dist
  - echo "conception-web.io" > CNAME
  - cp index.html 404.html
  - git add --all .
  - git commit --message "Automatically update from travis-ci"
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages
  - cat ./test/unit/coverage/lcov.info | ./node_modules/.bin/coveralls

# Note: you should set Environment Variables here or 'Settings' on travis-ci.org
env:
  global:
    - GH_REF: github.com/eldorplus/conception-website.git
    # - GH_TOKEN: 'Your GitHub Personal access tokens, via https://github.com/settings/tokens'
    #Numéro de commande: 6869806464